# =============================================================================
# BCallometryR — bc_species_codes dataset
#
# Builds a lookup table of detailed BC inventory species codes → SP0 codes
# used in the BC volume compilation system (taper_coefs_kbec / tree_volume).
#
# Source: lookup_species() function from FAIBBase R package
#   (bcgov/FAIBBase, authored by Yong Luo, NRCan/BC MoF)
#   BC Ministry of Forests species coding conventions.
#   Copyright 2019 Province of British Columbia, licensed under the
#   Apache License, Version 2.0.  Transcribed and reshaped 2026 by
#   Natural Resources Canada.
# =============================================================================

library(usethis)

raw <- matrix(ncol = 5, byrow = TRUE,
  # SPECIES  SP0    DESCRIPTION                   SP_SINDEX  SP_TYPE
  data = c(
  "A",    "AC",  "Cottonwood",                  "AT",       "D",
  "AC",   "AC",  "Poplar",                      "ACT",      "D",
  "ACB",  "AC",  "Balsam Poplar",               "ACB",      "D",
  "ACT",  "AC",  "Black Cottonwood",            "ACT",      "D",
  "AD",   "AC",  "Southern Cottonwood",         "ACT",      "D",
  "AH",   "AC",  "Poplar Cottonwood/Hybrid",    "ACT",      "D",
  "AT",   "AT",  "Trembling Aspen",             "AT",       "D",
  "AX",   "AC",  "Hybrid Poplar",               "ACB",      "D",
  "B",    "B",   "Balsam",                      "BA",       "C",
  "BA",   "B",   "Amabilis Fir",                "BA",       "C",
  "BB",   "B",   "Balsam Fir",                  "BL",       "C",
  "BC",   "B",   "White Fir",                   "BA",       "C",
  "BG",   "B",   "Grand Fir",                   "BA",       "C",
  "BL",   "B",   "Subalpine Fir",               "BL",       "C",
  "BM",   "B",   "Shasta Red Fir",              "BA",       "C",
  "BP",   "B",   "Noble Fir",                   "BP",       "C",
  "C",    "C",   "Cedar",                       "CW",       "C",
  "CI",   "C",   "Incense Cedar",               "CW",       "C",
  "CP",   "C",   "Port-Orford Cedar",           "CW",       "C",
  "CW",   "C",   "Western Red Cedar",           "CW",       "C",
  "CY",   "Y",   "Yellow Cedar",                "CW",       "C",
  "D",    "D",   "Alder",                       "DR",       "D",
  "DG",   "D",   "Sitka Alder",                 "DR",       "D",
  "DM",   "D",   "Mountain Alder",              "DR",       "D",
  "DR",   "D",   "Red Alder",                   "DR",       "D",
  "DS",   "D",   "Sitka Alder",                 "DR",       "D",
  "E",    "E",   "Birch",                       "AT",       "D",
  "EA",   "E",   "Alaska Paper Birch",          "AT",       "D",
  "EB",   "E",   "Scrub Birch",                 "AT",       "D",
  "EE",   "E",   "European Birch",              "AT",       "D",
  "EP",   "E",   "Paper Birch",                 "EP",       "D",
  "ES",   "E",   "Silver Birch",                "AT",       "D",
  "EW",   "E",   "Water Birch",                 "AT",       "D",
  "EXP",  "E",   "Alaska x Paper Birch Hybrid", "AT",       "D",
  "EY",   "E",   "Yellow Birch",                "AT",       "D",
  "F",    "F",   "Douglas-Fir",                 "FD",       "C",
  "FD",   "F",   "Douglas-Fir",                 "FD",       "C",
  "FDC",  "F",   "Coastal Douglas-Fir",         "FDC",      "C",
  "FDI",  "F",   "Interior Douglas-Fir",        "FDI",      "C",
  "G",    "MB",  "Dogwood",                     "DR",       "D",
  "GP",   "MB",  "Pacific Dogwood",             "DR",       "D",
  "H",    "H",   "Hemlock",                     "HW",       "C",
  "HM",   "H",   "Mountain Hemlock",            "HM",       "C",
  "HW",   "H",   "Western Hemlock",             "HW",       "C",
  "HXM",  "H",   "Mountain x Western Hemlock",  "HWC",      "C",
  "IG",   "C",   "Giant Sequoia",               "CW",       "C",
  "IS",   "C",   "Coast Redwood",               "CW",       "C",
  "J",    "C",   "Juniper",                     "CW",       "C",
  "JR",   "C",   "Rocky Mountain Juniper",      "CW",       "C",
  "K",    "E",   "Cascara",                     "AT",       "D",
  "KC",   "E",   "Cascara",                     "AT",       "D",
  "L",    "L",   "Larch",                       "LW",       "C",
  "LA",   "L",   "Alpine Larch",                "LW",       "C",
  "LD",   "L",   "Dahurian Larch",              "LW",       "C",
  "LE",   "L",   "Eastern Larch",               "LW",       "C",
  "LT",   "L",   "Tamarack",                    "LW",       "C",
  "LW",   "L",   "Western Larch",               "LW",       "C",
  "M",    "MB",  "Maple",                       "DR",       "D",
  "MB",   "MB",  "Bigleaf Maple",               "DR",       "D",
  "ME",   "E",   "Box Elder",                   "DR",       "D",
  "MN",   "MB",  "Norway Maple",                "DR",       "D",
  "MR",   "MB",  "Douglas Maple",               "DR",       "D",
  "MS",   "MB",  "Sycamore Maple",              "DR",       "D",
  "MV",   "MB",  "Vine Maple",                  "DR",       "D",
  "OA",   "C",   "Incense-Cedar",               "CW",       "C",
  "OB",   "C",   "Giant Sequoia",               "CW",       "C",
  "OC",   "C",   "Coast Redwood",               "CW",       "C",
  "OD",   "MB",  "European Mountain-Ash",       "AT",       "D",
  "OE",   "MB",  "Siberian Elm",                "AT",       "D",
  "OF",   "MB",  "Common Pear",                 "AT",       "D",
  "OG",   "MB",  "Oregon Ash",                  "AT",       "D",
  "OH",   "MB",  "White Ash",                   "AT",       "D",
  "OI",   "MB",  "Shagbark Hickory",            "AT",       "D",
  "P",    "PL",  "Pine",                        "PL",       "C",
  "PA",   "PA",  "Whitebark Pine",              "PL",       "C",
  "PF",   "PW",  "Limber Pine",                 "PL",       "C",
  "PJ",   "PL",  "Jack Pine",                   "PL",       "C",
  "PL",   "PL",  "Lodgepole Pine",              "PL",       "C",
  "PLC",  "PL",  "Shore Pine",                  "PL",       "C",
  "PLI",  "PL",  "Lodgepole Pine Interior",     "PL",       "C",
  "PM",   "PW",  "Monterey Pine",               "PL",       "C",
  "PR",   "PW",  "Red Pine",                    "PL",       "C",
  "PS",   "PW",  "Sugar Pine",                  "PL",       "C",
  "PW",   "PW",  "Western White Pine",          "PW",       "C",
  "PXJ",  "PL",  "Lodgepole x Jack Pine",       "PL",       "C",
  "PY",   "PY",  "Ponderosa Pine",              "PY",       "C",
  "Q",    "MB",  "Oak",                         "AT",       "D",
  "QE",   "MB",  "English Oak",                 "AT",       "D",
  "QG",   "MB",  "Garry Oak",                   "AT",       "D",
  "QW",   "MB",  "White Oak",                   "AT",       "D",
  "R",    "MB",  "Arbutus",                     "DR",       "D",
  "RA",   "MB",  "Arbutus",                     "DR",       "D",
  "S",    "S",   "Spruce",                      "S",        "C",
  "SA",   "S",   "Norway Spruce",               "SW",       "C",
  "SB",   "S",   "Black Spruce",                "SB",       "C",
  "SE",   "S",   "Engelmann Spruce",            "SE",       "C",
  "SN",   "S",   "Norway Spruce",               "SW",       "C",
  "SS",   "S",   "Sitka Spruce",                "SS",       "C",
  "SW",   "S",   "White Spruce",                "SW",       "C",
  "SX",   "S",   "Spruce Hybrid",               "SW",       "C",
  "SXB",  "S",   "Spruce glauca x mariana",     "SW",       "C",
  "SXE",  "S",   "Sitka x Engelmann Spruce",    "SS",       "C",
  "SXL",  "S",   "Sitka x White Spruce",        "SS",       "C",
  "SXS",  "S",   "Sitka and Unknown Spruce",    "SS",       "C",
  "SXW",  "S",   "White x Engelmann Spruce",    "SW",       "C",
  "SXX",  "S",   "Spruce glauca x engelmannii", "SW",       "C",
  "T",    "H",   "Yew",                         "HWC",      "C",
  "TW",   "H",   "Pacific Yew",                 "HWC",      "C",
  "U",    "E",   "Apple",                       "AT",       "D",
  "UA",   "E",   "Apple",                       "AT",       "D",
  "UP",   "E",   "Pacific Crab Apple",          "AT",       "D",
  "V",    "E",   "Cherry",                      "AT",       "D",
  "VB",   "E",   "Bitter Cherry",               "AT",       "D",
  "VP",   "E",   "Pin Cherry",                  "AT",       "D",
  "VS",   "E",   "Sweet Cherry",                "AT",       "D",
  "VV",   "E",   "Choke Cherry",                "AT",       "D",
  "W",    "E",   "Willow",                      "AT",       "D",
  "WA",   "E",   "Peachleaf Willow",            "AT",       "D",
  "WB",   "E",   "Bebb's Willow",               "AT",       "D",
  "WD",   "E",   "Pussy Willow",                "AT",       "D",
  "WP",   "E",   "Pacific Willow",              "AT",       "D",
  "WS",   "E",   "Scouler's Willow",            "AT",       "D",
  "WT",   "E",   "Sitka Willow",                "AT",       "D",
  "X",    "F",   "Unknown Tree",                "FD",       "C",
  "XC",   "F",   "Unknown Conifer",             "FD",       "C",
  "XH",   "E",   "Unknown Hardwood",            "AT",       "D",
  "Y",    "Y",   "Cypress",                     "CW",       "C",
  "YC",   "Y",   "Yellow Cedar",                "CW",       "C",
  "YP",   "Y",   "Port Orford-Cedar",           "CW",       "C",
  "Z",    "E",   "Other Tree, Not On List",     "FD",       "D",
  "ZC",   "F",   "Other Conifer",               "FD",       "C",
  "ZH",   "E",   "Other Hardwood",              "AT",       "D"
))

bc_species_codes <- as.data.frame(raw, stringsAsFactors = FALSE)
names(bc_species_codes) <- c("species_code", "sp0", "description",
                              "sp_sindex", "sp_type")

cat(sprintf("bc_species_codes: %d rows, %d unique species_codes, %d SP0 groups\n",
            nrow(bc_species_codes),
            length(unique(bc_species_codes$species_code)),
            length(unique(bc_species_codes$sp0))))

usethis::use_data(bc_species_codes, overwrite = TRUE)
